
baseURL = 'http://localhost:1313'

locale = 'de-DE'
defaultContentLanguage = 'de'

[languages]
  [languages.de]
    locale = 'de-DE'
    label = 'Deutsch'
    weight = 1

title = 'gh-pages deploy-Skript'
theme = 'github.com/jpanther/congo/v2'

[module]
  [[module.imports]]
    path = 'github.com/jpanther/congo/v2'

[params.homepage]
  layout = 'page'
  showRecent = true
  recentLimit = 5